import React from 'react'
import styled from 'styled-components'

const HowToContainer = styled.div`
padding: 75px 100px;
background-color: rgba(20,110,180,.05);
display: flex;
justify-content: space-around;
align-items: stretch;
.item{
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-start;
    margin : 0 1rem;
}
.item h3{
    margin: 1rem 0 ;
}
.item p{
    line-height: 1.8;
}
@media (max-width : 900px) {
    padding:  75px 50px;
}
@media (max-width : 768px){
    padding: 75px 100px;
    flex-direction: column;

    .item{
        align-items: flex-start;
        margin-bottom: 1.2rem;
    }

}
@media (max-width : 576px){
    padding: 75px 20px;

    .item{
        align-items: center;
    }
}
`
const HowTo = () => {
    const obj = [
        {
            name : 'Search',
            img : '/icons/3.svg',
            description : 'Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.'
        },
        {
            name : 'Select',
            img : '/icons/1.svg',
            description : 'Choose from thousands of options generated by the slogan maker that fit your needs.'
        },
        {
            name : 'Standout',
            img : '/icons/2.svg',
            description : "Congrats on your new slogan. It's time to win the world!"
        }
    ]
  return (
   <HowToContainer>
    {
        obj.map((item,indx)=>(<div className='item' key={indx}>
           <img src={item.img} alt="" />
           <h3>{item.name}</h3>
           <p>{item.description}</p>
        </div>))
    }
   </HowToContainer>
  )
}

export default HowTo